# .goreleaser.yaml
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: odyssey-cli

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

builds:
  - main: ./cli
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X github.com/algebananazzzzz/odyssey/cli/constants.Version={{.Version}}
      - -X github.com/algebananazzzzz/odyssey/cli/constants.CommitSHA={{.Commit}}
      - -X github.com/algebananazzzzz/odyssey/cli/constants.BuildDate={{.Date}}

release:
  make_latest: true
  mode: append

