# project.config.yaml
# Maps each project type to infra, CICD, project files, and extra single files.

projects:
  vpc:
    name: 3 Tier VPC
    files:
      infra: infra/vpc
      cicd: cicd-templates/terraform-resources

  # lambda_api_gw:
  #   name: Serverless API (Lambda + API Gateway)
  #   infra: infra/lambda_api_gw
  #   cicd: cicd-templates/lambda_api_gw
  #   project_files: project-files/lambda_api_gw

  scheduled_job:
    name: Scheduled Job (Lambda + EventBridge)
    infra: infra/schedule_job
    cicd: cicd-templates/docker_lambda
    project_files: project-files/schedule_job

  scheduled_puppeteer_job:
    name: Scheduled Puppeteer Job (for web scraping)
    infra: infra/schedule_job
    cicd: cicd-templates/docker_lambda
    project_files: project-files/puppeteer_web_scraper
