# .github/workflows/preprod-release-tag.yml
name: Pre-Production Tag Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc'

jobs:
  infra-deploy-preprod:
    name: Provision Infrastructure (Production)
    runs-on: ubuntu-latest
    environment: preprod

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: ⚙️ Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"

      - name: 🚀 Apply Terraform for Production Infra
        id: deploy
        working-directory: infra
        run: |
          terraform init -input=false
          terraform workspace select -or-create preprod-app
          terraform plan --var-file=config/preprod.tfvars -out=output.tfplan -input=false
          terraform apply -input=false --auto-approve output.tfplan
