# .github/workflows/ci-feature-branch.yml
name: Feature Branch CI (infra)

# Triggers:
# - Manual trigger via GitHub UI from branches (workflow_dispatch)
# - Automatic on pushes to specific feature branches
on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/**'
      - 'feature/**'
      - 'JIRA/**'
    # hotfix: trigger only when infra files change.
    # consider ways to do this for seperate jobs
    paths:
      - infra/**

jobs:
  lint-and-unit-tests:
    name: Static Analysis & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: 1. ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: 2. ⚙️ Setup Terraform Cli
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"

      - name: 3. 🧪 Check Terraform Syntax
        working-directory: infra
        run: terraform fmt -check	

  terraform-docs:
    runs-on: ubuntu-latest
    needs: lint-and-unit-tests
    permissions:
      contents: write
    steps:
      - name: 1. ⬇️ Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: 2. ⚙️ Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22.0"

      - name: 3. ⚙️ Setup terraform-docs
        run: go install github.com/terraform-docs/terraform-docs@v0.20.0
      
      - name: 4. 📃 Generate Terraform markdown documentation
        run: $(go env GOPATH)/bin/terraform-docs markdown -c infra/terraform-docs.yml infra/
     
      - name: 5. 👻 Commit documentation to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "👻 (Module READMEs): Automated Terraform Documentation"
